### ISSUE TITLE
CMake failed because of nlohmann_json

### ISSUE THREAD

**Issue by PicksPeng** [iic-jku/ddsim#10]
Hi,

I am trying to install DDSIM and cmake reported error when I am building qfr:
-- Using the single-header code from /home/user/ddsim/extern/qfr/extern/json/single_include/
CMake Error at src/CMakeLists.txt:112 (install):
  install TARGETS given target "nlohmann_json" which does not exist in this directory.

It seems like nlohmann has updated his json repo, since his new README/External section is using nlohmann_json::nlohmann_json.

I am building the codes on WSL2 ubuntu 18.04 LTS. My CMake version is 3.10.2.

I am not familiar with CMake so I am not sure how to fix it...

BTW the README of DDSIM repo doesn't mention the 'mkdir build & cd build' part, which seems a bit misleading for me to find it out...

**Comment by burgholzer** [comment]
Hi there,

thanks for your interest in our project.
Regarding the README of the DDSIM repo: `mkdir build & cd build` is only required for CMake versions <3.13. I added a corresponding hint in the README.

Concerning your real error: I can't quite reproduce it on a fresh git clone or our CI builds. Are you sure you did a **recursive** submodule update (`git submodule update --init --recursive`) after cloning? This is necessary in order to clone all the submodules of the sub-projects. Alternatively you could try a fresh clone of the project and add the `--recurse-submodules` flag.

**Comment by PicksPeng** [comment]
Hi,

The problem is caused by the old version of CMake. I updated my CMake and the problem is gone.

Known valid CMake version (in my tests): 3.13, 3.19.

Ubuntu 18.04 LTS's default CMake version is 3.10.

Thanks.
